@startuml

!include skinparam.puml

title Diagramme de classe P7

class Project {
    name: string
    startDate: dateTime
    deadline: dateTime
    active: boolean
}

enum Status {
    TODO
    DOING
    DONE
}

class Tag {
    name: string
}

class Task {
    name: string
    description: string
    deadline: dateTime
}

class User {
    lastname: string
    firstname: string
    email: string
    password: string
    role: integer
    contract: string
    contractStartDate: dateTime
    active: boolean
}

class WorkingTime {
    startDate: dateTime
    endDate: dateTime
}

Project "1" -down- "*" Task
Project "1" -right- "*" Tag
Project "*" -left- "*" User
Project "*" -left- "1" Status

User "0..1" -right- "*" Task
User "1" -- "*" WorkingTime

Task "*" -up- "1" Status
Task "*" -up- "*" Tag
Task "1" -down- "*" WorkingTime

@enduml
